name: strazzabosco
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40136
title: Solution Provider
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2666af'
    - '#a8acac'
    - '#231f20'
    - '#4e4b4c'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
